apiVersion: kubeflow.org/v1beta1
kind: TFJob
metadata:
  name: tfjob-retrain-aci
spec:
  tfReplicaSpecs:
    MASTER:
      replicas: 1
      template:
        metadata:
          annotations:
            virtual-kubelet.io/gpu-type: K80 # For ACI GPU
        spec:
          containers:
            - image: ritazh/image-retrain-kubecon:1.9-gpu
              name: tensorflow
              command: ["python", "retrain.py"] # For ACI container group
              args:                
                - "--bottleneck_dir=/tf-output/bottlenecks"
                - "--model_dir=/tf-output/inception"
                - "--summaries_dir=/tf-output/training_summaries/baseline"
                - "--output_graph=/tf-output/retrained_graph.pb"
                - "--output_labels=/tf-output/retrained_labels.txt"
                - "--saved_model_dir=/tf-output/saved_models/1"
                - "--image_dir=images"        
              resources:
                requests:
                  memory: 10G
                  cpu: 2
                limits:
                  nvidia.com/gpu: 1
                  memory: 10G
                  cpu: 2
              volumeMounts:
                - mountPath: /tf-output
                  name: azure-files
          restartPolicy: OnFailure
          volumes:
            - name: azure-files
              azureFile:
                secretName: azure-file-secret
                shareName: datak80
                readOnly: false
          nodeSelector: # For VK
            kubernetes.io/role: agent
            beta.kubernetes.io/os: linux
            type: virtual-kubelet
          tolerations: # For VK
          - key: virtual-kubelet.io/provider
            operator: Exists
          - key: azure.com/aci
            effect: NoSchedule